In [1]:
#import packages
import pandas as pd

In [2]:
main_data = pd.read_csv("Main-dataset.csv")

In [3]:
main_data.head()

,Unnamed: 0,measure,location,sex,age,cause,rei_value,metric,year,val,upper,lower,rei_type
0,3060356,DALYs (Disability-Adjusted Life Years),Saudi Arabia,Male,Age-standardized,Cardiovascular diseases,Low physical activity,Percent,2007,0.110321,0.171326,0.056011,Risk
1,3060357,DALYs (Disability-Adjusted Life Years),Saudi Arabia,Female,Age-standardized,Cardiovascular diseases,Low physical activity,Percent,2007,0.102372,0.157230,0.051618,Risk
2,3060358,DALYs (Disability-Adjusted Life Years),Saudi Arabia,Male,Age-standardized,Cardiovascular diseases,Low physical activity,Rate,2007,703.274450,1119.290595,352.861106,Risk
3,3060359,DALYs (Disability-Adjusted Life Years),Saudi Arabia,Female,Age-standardized,Cardiovascular diseases,Low physical activity,Rate,2007,515.773840,799.603692,264.825042,Risk
4,3060360,DALYs (Disability-Adjusted Life Years),Saudi Arabia,Male,95 plus,Cardiovascular diseases,Low physical activity,Number,2007,85.853783,131.956869,43.554401,Risk

In [4]:
second_data = pd.read_csv("Supplemental-dataset.csv")

In [5]:
second_data.head()

,Unnamed: 0,measure,location,sex,age,cause,rei_value,metric,year,val,upper,lower,rei_type
0,0,DALYs (Disability-Adjusted Life Years),Portugal,Female,Age-standardized,Neoplasms,Air pollution,Percent,2017,0.005371,0.010512,0.000505,Risk
1,1,DALYs (Disability-Adjusted Life Years),Portugal,Male,Age-standardized,Neoplasms,Air pollution,Rate,2017,43.307932,83.712949,3.006556,Risk
2,2,DALYs (Disability-Adjusted Life Years),Portugal,Female,Age-standardized,Neoplasms,Air pollution,Rate,2017,11.247712,22.107788,1.026266,Risk
3,3,DALYs (Disability-Adjusted Life Years),Portugal,Male,Age-standardized,Neoplasms,Other environmental risks,Percent,2017,0.008595,0.022147,0.001467,Risk
4,4,DALYs (Disability-Adjusted Life Years),Portugal,Female,Age-standardized,Neoplasms,Other environmental risks,Percent,2017,0.004026,0.010284,0.000687,Risk

In [7]:
#countries
second_data.location.value_counts()

Saudi Arabia                      4532
Guam                              3364
Bosnia and Herzegovina            3352
Tonga                             3350
Czech Republic                    3342
Uzbekistan                        3302
Papua New Guinea                  3302
Burkina Faso                      3292
Vietnam                           3292
Cameroon                          3288
Kiribati                          3286
Maldives                          3280
Mongolia                          3280
Indonesia                         3278
Mauritius                         3274
Georgia                           3274
Sierra Leone                      3270
South Korea                       3262
Nigeria                           3262
Mali                              3260
Latvia                            3250
Yemen                             3246
Russian Federation                3240
Tunisia                           3238
Pakistan                          3236
Sri Lanka                         3234
Montenegro                        3234
South Africa                      3232
Taiwan                            3232
Jordan                            3230
                                  ...
South Sudan                       3140
Eritrea                           3134
Macedonia                         3124
Somalia                           3124
Cote d'Ivoire                     3124
Togo                              3124
Malaysia                          3118
Chad                              3116
Benin                             3112
Zambia                            3112
Swaziland                         3112
Cape Verde                        3110
Niger                             3106
Central African Republic          3096
Burundi                           3096
Azerbaijan                        3094
Fiji                              3090
Senegal                           3088
Mozambique                        3088
Madagascar                        3088
North Korea                       3076
Croatia                           3068
Kyrgyzstan                        3058
Albania                           3048
Philippines                       3044
Turkmenistan                      3040
Timor-Leste                       3032
Solomon Islands                   3028
Cambodia                          3024
Federated States of Micronesia    3020
Name: location, Length: 195, dtype: int64

In [8]:
#years, data is from 2007 to 2017
second_data.year.value_counts()

2017    80338
2016    80338
2015    80338
2014    80338
2008    80338
2007    80338
2013    64224
2009    31802
2012    14584
2011    13604
2010    13604
Name: year, dtype: int64

In [9]:
second_data.cause.value_counts()
#Self-harm and interpersonal violence, 24664

Diarrheal diseases                              111540
Cardiovascular diseases                          60862
Neoplasms                                        58116
Diabetes and kidney diseases                     54946
Lower respiratory infections                     34320
Respiratory infections and tuberculosis          32828
Sense organ diseases                             24798
Self-harm and interpersonal violence             24664
Chronic respiratory diseases                     22144
Digestive diseases                               22140
Musculoskeletal disorders                        22120
Neurological disorders                           22092
Transport injuries                               22000
Unintentional injuries                           21984
Substance use disorders                          16472
Mental disorders                                 13784
HIV/AIDS and sexually transmitted infections     13730
Other infectious diseases                        11004
Enteric infections                               10984
Maternal and neonatal disorders                   8262
Nutritional deficiencies                          5548
Other non-communicable diseases                   5508
Name: cause, dtype: int64

In [10]:
main_data.cause.value_counts()
#Self-harm and interpersonal violence,528

Diarrheal diseases                              18590
Lower respiratory infections                     5720
Neoplasms                                        1452
Diabetes and kidney diseases                     1364
Cardiovascular diseases                          1342
Respiratory infections and tuberculosis           924
Chronic respiratory diseases                      572
Digestive diseases                                572
Sense organ diseases                              561
Self-harm and interpersonal violence              528
Substance use disorders                           528
Unintentional injuries                            506
Transport injuries                                506
Neurological disorders                            506
HIV/AIDS and sexually transmitted infections      440
Mental disorders                                  440
Musculoskeletal disorders                         440
Enteric infections                                286
Other infectious diseases                         286
Maternal and neonatal disorders                   231
Nutritional deficiencies                          176
Other non-communicable diseases                   110
Name: cause, dtype: int64

In [11]:
#Alcohol use
#Drug use
#High body-mass index
#High systolic blood, pressure
#Tobacco smoking
#Physical inactivity and low physical activity
#
#حالة الوالدين التعليمية
#حالة الوالدين الاجتماعي

1. Self-harm by firearm
2. Self-harm by other specified
means
3. Interpersonal violence Physical violence by firearm
4. Physical violence by sharp object
5. Sexual violence
6. Physical violence by other means

### Risks
* Behavioral risks
* Child and maternal malnutrition
* Tobacco
* Alcohol use
* Drug use
* Dietary risks
* Intimate partner violence
* Childhood maltreatment
* Unsafe sex
* Low physical activity

### Solutions:
* وضع قوانين و تطبيقها فعلياً 
* الوصول للمناطق النائية
* توعية المعرضين لخطر العنف بحقوقهم
* وصل مستشارين و اخصائيين نفسيين للمتعرضين للعنف 
* في حال قررنا يكون حلنا لمشلكة العنف تطبيق، نحتاج نستعجل في ايجاد العلاقة

في التقرير المقدم، ينبغي شرح الفكرة بوضوح. حيث يوضح فيه الفريق المشكلة المراد تقديم حل لها. بعد تحليل البيانات، قم بتحديد مشكلة محددة، قدم وصفاً دقيقا لها، بين الأسس المستخدمة لتحديدها، ثم اقترح حلولاً مناسبة.  
قدم شرحاً مفصلاً للحل الذي ترغب بتقديمه، بين نوع هذا  الحل، هل يتضمن الحل تغيير في قانون؟ نظام؟تطوير برنامج؟ … إلخ

### Questions:
* ...........
* ...........
* ...........
* ...........
* ...........
* ...........
* ...........